[33.001899719] 2019-03-06 20:35:11,156 - INFO - launcher: Starting sanity checks
[34.002065659] 2019-03-06 20:35:11,157 - INFO - launcher: Checking for Python 3.5+
[34.002065659] 2019-03-06 20:35:11,157 - INFO - launcher: Checking console encoding
[34.002065659] 2019-03-06 20:35:11,157 - INFO - launcher: Setting console encoding to UTF-8
[34.002065659] 2019-03-06 20:35:11,157 - INFO - launcher: Ensuring we're in the right environment
[35.002231598] 2019-03-06 20:35:11,158 - INFO - launcher: Adding local bins/ folder to path
[672.038555145] 2019-03-06 20:35:11,795 - INFO - launcher: Required checks passed.
[673.038721085] 2019-03-06 20:35:11,796 - INFO - launcher: Optional checks passed.
[673.038721085] 2019-03-06 20:35:11,796 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.2320704460144043] 2019-03-06 20:35:12,355 - WARNING - musicbot.config | In config.py::MainThread(7836), line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.2320704460144043] 2019-03-06 20:35:12,355 - INFO - musicbot.config | In config.py::MainThread(7836), line 127 in run_checks: Using i18n: config/i18n/en.json
[1.2340705394744873] 2019-03-06 20:35:12,357 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 226 in _setup_logging: Set logging level to INFO
[1.2360708713531494] 2019-03-06 20:35:12,359 - DEBUG - musicbot.json | In json.py::MainThread(7836), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.2690725326538086] 2019-03-06 20:35:12,392 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 91 in __init__: Starting MusicBot 1.9.8_4
[1.2700726985931396] 2019-03-06 20:35:12,393 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 97 in __init__: Loaded autoplaylist with 2531 entries
[4.0042293071746826] 2019-03-06 20:35:15,127 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 922 in on_ready: Connection established, ready to go.
[4.0042293071746826] 2019-03-06 20:35:15,127 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 340 in _cache_app_info: Caching app info
[4.1492373943328857] 2019-03-06 20:35:15,272 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 744 in _scheck_ensure_env: Ensuring data folders exist
[4.1502373218536377] 2019-03-06 20:35:15,273 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 760 in _scheck_server_permissions: Checking server permissions
[4.1502373218536377] 2019-03-06 20:35:15,273 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 764 in _scheck_autoplaylist: Auditing autoplaylist
[4.1502373218536377] 2019-03-06 20:35:15,273 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 768 in _scheck_configs: Validating config
[4.1502373218536377] 2019-03-06 20:35:15,273 - DEBUG - musicbot.config | In config.py::MainThread(7836), line 217 in async_validate: Validating options...
[4.1502373218536377] 2019-03-06 20:35:15,273 - DEBUG - musicbot.bot | In bot.py::MainThread(7836), line 771 in _scheck_configs: Validating permissions config
[4.1512374877929688] 2019-03-06 20:35:15,274 - DEBUG - musicbot.permissions | In permissions.py::MainThread(7836), line 94 in async_validate: Validating permissions...
[4.1512374877929688] 2019-03-06 20:35:15,274 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 939 in on_ready: Connected: 552920919782195205/Bracia Golec#7701
[4.1522374153137207] 2019-03-06 20:35:15,275 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 947 in on_ready: Owner:     345123655170260994/Siekam CebulkÄ™#4968

[4.1532375812530518] 2019-03-06 20:35:15,276 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 950 in on_ready: Guild List:
[4.1532375812530518] 2019-03-06 20:35:15,276 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 954 in on_ready:  - Brygada SCP #1
[4.1542377471923828] 2019-03-06 20:35:15,277 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 1010 in on_ready: Not bound to any text channels
[4.1542377471923828] 2019-03-06 20:35:15,277 - INFO - musicbot.bot | In bot.py::MainThread(7836), line 1036 in on_ready: Not autojoining any voice channels
